### ISSUE TITLE
Where is the monarch_cuda file

### ISSUE THREAD

**Issue by jimmylihui** [HazyResearch/flash-fft-conv#1]
I want to run the test, but there is no monarch_cuda.py file.

**Comment by Kumbong** [comment]
Hi, did you follow the setup instructions on the readme? and how are you running the tests?

**Comment by jimmylihui** [comment]
I am using the server, but I can't update server to 12.1. So I want to see if there is a way around.

**Comment by jimmylihui** [comment]
By the way how to shape kf into N1x N1
![Uploading copy.png…]()

**Comment by jimmylihui** [comment]
And what is the value of twiddle factor, is it initialized?

**Comment by DanFu09** [comment]
Hi, thanks for your interest!

FlashFFTConv is a library for FFT convolution on GPU. We release it as a [PyTorch CUDA extension](https://pytorch.org/tutorials/advanced/cpp_extension.html), so most of the code is in CUDA.

You can see the interface to the CUDA in [monarch.cpp](https://github.com/HazyResearch/flash-fft-conv/blob/main/csrc/flashfftconv/monarch.cpp). The instructions under [installation](https://github.com/HazyResearch/flash-fft-conv/tree/main#installation) compile and install the CUDA code.

It may work with older versions of CUDA toolkit, but we haven't tested - if you try it out please let us know.

> And what is the value of twiddle factor, is it initialized?

The Twiddle factors are initialized in PyTorch. You can see example calls [here](https://github.com/HazyResearch/flash-fft-conv/blob/main/flashfftconv/conv.py#L88), and go through that file for all the sequence lengths.
