### ISSUE TITLE
Can we install FlashFFTConv by pip?

### ISSUE THREAD

**Issue by Hambaobao** [HazyResearch/flash-fft-conv#13]
Hi, thanks for your great work. Can we directly install `FlashFFTConv` through `pip`, for example, using a command like:
`pip install git+https://github.com/HazyResearch/flash-fft-conv.git`?

**Comment by Hambaobao** [comment]
> Hi, thanks for your great work. Can we directly install `FlashFFTConv` through `pip`, for example, using a command like:
> `pip install git+https://github.com/HazyResearch/flash-fft-conv.git`?

I tried `pip install git+https://github.com/HazyResearch/flash-fft-conv.git#subdirectory=csrc/flashfftconv`, and it seems worked.😂

**Comment by DanFu09** [comment]
Cool! I’ll add it to the Readme!

**Comment by Hambaobao** [comment]
> Cool! I’ll add it to the Readme!
> […](#)

Sorry, my mistake, it seems like it's still not installed correctly. 🤣

**Comment by Hambaobao** [comment]
> > Cool! I’ll add it to the Readme!
> > […](#)
> 
> Sorry, my mistake, it seems like it's still not installed correctly. 🤣

Alright, I have solved it.😬 We need to do two steps:
1. `pip install git+https://github.com/HazyResearch/flash-fft-conv.git#subdirectory=csrc/flashfftconv`;
2. `pip install git+https://github.com/HazyResearch/flash-fft-conv.git`;

Done! ✨
